module.exports = {
	Help: require('./help'),
	Ping: require('./ping'),
	Avatar: require('./avatar'),
	Hackedandbanned: require('./hackedandbanned'),
	Shop: require('./shop'),
	Buy: require('./buy'),
	Use: require('./use'),
	Trade: require('./trade'),
	Profile: require('./profile'),
	Daily: require('./daily'),
	Leaderboard: require('./leaderboard'),
	Gamble: require('./gamble'),
	Invite: require('./invite'),
	Play: require('./play'),
	Queue: require('./queue'),
	Skip: require('./skip'),
	Add: require('./add'),
	Ban: require('./ban'),
	Reload: require('./reload'),
	Delete: require('./delete'),
	Reply: require('./reply')
};
